config/routes.rb
Rails.application.routes.draw do
  resources :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_slack_client

  def new
    @channels = @client.channels
  end

  def create
    channel_ids_hash.each do |_, channel_id|
      @client.post_message(channel: channel_id, text: message, as_user: true)
    end
    redirect_to new_message_url, notice: "Success post messages"
  end

  private
  
  def set_slack_client
    @client = SlackApi.new
  end

  def message_params
    params.permit(:message, channel_ids: [])
  end

  def channel_ids_hash
    params[:channel_ids]
  end

  def message
    params[:message]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackBoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<%= form_with url: messages_path, local: true do |form| %>
  <% @channels.each.with_index do |channel, i| %>
    <%= form.hidden_field "channel_ids[#{i}]", value: channel.id %>
  <% end %>

  <div class="field">
    <%= form.text_area :message, rows: 5, required: true %>
  </div>
  <%= form.submit "投稿" %>
<% end %>